on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: build-${{ github.ref_name }}
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  get-changed-projects:
    uses: ./.github/workflows/call-get-changed-projects.yml

  build:
    needs: get-changed-projects
    strategy:
      fail-fast: false # To avoid cancellation of other jobs
      matrix:
        project: ${{ fromJSON(needs.get-changed-projects.outputs.projects) }}
    uses: ./.github/workflows/call-build-project.yml
    with:
      project: ${{ matrix.project }}
      sha: ${{github.event.pull_request.head.sha}}
    secrets: inherit

  build-completion:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Build completion
        run: echo "Build completion"
